### ISSUE TITLE
Update maintainer's website domain address in index.html

### ISSUE THREAD

**Issue by suriyaa** [SuriyaaKudoIsc/animate-a-name#25]
Please update the URL in [**`index.html`**](https://github.com/SuriyaaKudoIsc/animate-a-name/blob/gh-pages/index.html#L34) from `https://bit.ly/Suriyaa` to `https://about.suriyaa.tk/`.

**Comment by zootechdrum** [comment]
Hello, is anyone working on this. I see a pull request that is still open.
