### ISSUE TITLE
Remove Hubot package from package.json

### ISSUE THREAD

**Issue by suriyaa** [SuriyaaKudoIsc/animate-a-name#7]
Enable Hubot in this project and check if it works.

> It's already listed in the [`package.json`](https://github.com/SuriyaaKudoIsc/animate-a-name/blob/gh-pages/package.json#L40)!

**Comment by supergr35** [comment]
Would we want any features other than the simple hubot ship it?

**Comment by suriyaa** [comment]
Do you have any suggestions? 😃

**Comment by zahiryahya1** [comment]
Hi I am a beginner at contributing to open source and I am a bit confused about what exactly you want.   Ive been researching hubot and from what i read, its used for communication. I dont see/understand the purpose of it in this project because hubot-shipit just posts pictures. Can you explain what the goal is?

**Comment by suriyaa** [comment]
@zahiryahya1 This should be a helpful function for posting emoji pictures in commits or on pull requests.

**Comment by suriyaa** [comment]
@zahiryahya1 @supergr35 If you want you can remove the Hubot package from [`package.json`](https://github.com/SuriyaaKudoIsc/animate-a-name/blob/gh-pages/package.json#L41-L43). 😃

**Comment by koderproxy** [comment]
i would like to take this problem

**Comment by soumyanjaleemahapatra** [comment]
@koderproxy are you still working on it? If not, I could take up this issue @SuriyaaKudoIsc

**Comment by koderproxy** [comment]
You take this

**Comment by soumyanjaleemahapatra** [comment]
just to make sure if I have understood it correctly, the idea is to remove Hubot from the package.json file?

**Comment by suriyaa** [comment]
@soumyanjaleemahapatra This issue was already fixed in #16 by @zahiryahya1.
