### ISSUE TITLE
Improve PageSpeed

### ISSUE THREAD

**Issue by suriyaa** [SuriyaaKudoIsc/animate-a-name#9]
Improve the PageSpeed of the Animate-A-Name website: https://animate-a-name.tk/.

> Check the current situation: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fanimate-a-name.tk%2F

To do list:

- [x] Fix "above the fold" issue
- [x] Fix render blocking for JavaScript files
- [x] Fix render blocking for CSS files

**Comment by tyricec** [comment]
Hi, I would like to check this out. Any ideas on how I would test this?

I'm thinking that I would have to host the page somewhere else (most likely github page) and run the tool with that host.

**Comment by suriyaa** [comment]
@tyricec Ok. The source code is available here: https://github.com/SuriyaaKudoIsc/animate-a-name.

----

### Helpful resources
- To fix the "above the fold" issue use this tool: https://jonassebastianohlsson.com/criticalpathcssgenerator/
- To fix render blocking for JS files read: https://varvy.com/pagespeed/render-blocking.html
- To fix render blocking for CSS files read: https://varvy.com/pagespeed/render-blocking-css.html

**Comment by tyricec** [comment]
Found out that the way to test is to use a tunnel app such as [ngrok](https://ngrok.com/). Pretty cool.
